version: "3.9"

services:

  auctionapp:
    build:
      context: .
    volumes:
      - .:/opt/app
    ports:
      - '8010:8010'

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - auctionapp
    ports:
      - '8020:8020'