version: "3.9"

services:

  app:
    build:
      context: .
    volumes:
      - .:/opt/app
    ports:
      - '8010:8010'
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - app
    ports:
      - '8020:8020'