name: "Ruby on Rails CI"

env:
  RUBY_VERSION: 3.2.0-preview1
  NODE_VERSION: 18.18.2
  BUNDLER_VERSION: 2.4.12
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install vips library
        run: sudo apt-get install -y libvips
        
      - name: Setup SQLite
        run: sudo apt-get install -y libsqlite3-dev
        
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}
          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Yarn install
        run: yarn install
        
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
        
      - name: Set up asset pipeline
        run: |
          yarn build
          yarn build:css
          
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}
          
      # Add or replace any other lints here
      - name: Security audit dependencies
        run: |
           gem install bundler-audit
           bundler-audit --update
           
      - name: Run Rubocop
        run: bundle exec rubocop -c .rubocop.yml

